# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Check dist/

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Rebuild the dist/ directory
        run: |
          yarn build
          yarn package

      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

      # push the dist/ directory to the current branch
      - name: Push changes to branch
        run: |
          git add dist/**
          
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git commit -m "Rebuild dist/ directory"
          git push origin ${{ github.ref }}